version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directories:
      - /cli
      - /app/server
      - /app/dashboard
    schedule:
      interval: weekly
    groups:
      docker:
        patterns: ["*"]

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    groups:
      bun:
        patterns: ["*"]
