import { defineConfig } from "tsup";

export default defineConfig({
	entry: {
		"api-key-api": "api-key-api.ts",
		client: "client.ts",
		duration: "duration.ts",
		event: "event.ts",
		"namespace-api": "namespace-api.ts",
		schedule: "schedule.ts",
		"schedule-api": "schedule-api.ts",
		retry: "retry.ts",
		serializable: "serializable.ts",
		sleep: "sleep.ts",
		symbols: "symbols.ts",
		task: "task.ts",
		trigger: "trigger.ts",
		utils: "utils.ts",
		validator: "validator.ts",
		worker: "worker.ts",
		workflow: "workflow.ts",
		"workflow-run": "workflow-run.ts",
		"workflow-api": "workflow-api.ts",
		"workflow-run-api": "workflow-run-api.ts",
	},
	format: ["esm"],
	dts: true,
	clean: true,
	outDir: "dist",
});
