import { defineConfig } from "tsup";

export default defineConfig({
	entry: {
		"api/api-key": "api/api-key.ts",
		"api/namespace": "api/namespace.ts",
		"api/schedule": "api/schedule.ts",
		"api/workflow": "api/workflow.ts",
		"api/workflow-run": "api/workflow-run.ts",
		client: "client.ts",
		"infra/cache": "infra/cache.ts",
		"infra/queue/index": "infra/queue/index.ts",
		"infra/timer": "infra/timer.ts",
		namespace: "namespace.ts",
		organization: "organization.ts",
		schedule: "schedule.ts",
		symbols: "symbols.ts",
		validator: "validator.ts",
		worker: "worker.ts",
		"workflow/index": "workflow/index.ts",
		"workflow/state-transition": "workflow/state-transition.ts",
		"workflow/task/index": "workflow/task/index.ts",
		"workflow/run/index": "workflow/run/index.ts",
	},
	format: ["esm"],
	dts: true,
	clean: true,
	outDir: "dist",
	noExternal: ["@aikirun/lib"],
});
