import { defineConfig } from "tsup";

export default defineConfig({
	entry: {
		"api/api-key": "src/api/api-key.ts",
		"api/namespace": "src/api/namespace.ts",
		"api/schedule": "src/api/schedule.ts",
		"api/workflow": "src/api/workflow.ts",
		"api/workflow-run": "src/api/workflow-run.ts",
		client: "src/client.ts",
		context: "src/context.ts",
		iam: "src/iam.ts",
		"infra/cache": "src/infra/cache.ts",
		"infra/db": "src/infra/db.ts",
		"infra/queue/index": "src/infra/queue/index.ts",
		"infra/timer": "src/infra/timer.ts",
		namespace: "src/namespace.ts",
		organization: "src/organization.ts",
		schedule: "src/schedule.ts",
		symbols: "src/symbols.ts",
		validator: "src/validator.ts",
		worker: "src/worker.ts",
		"workflow/index": "src/workflow/index.ts",
		"workflow/state-transition": "src/workflow/state-transition.ts",
		"workflow/task/index": "src/workflow/task/index.ts",
		"workflow/run/index": "src/workflow/run/index.ts",
	},
	format: ["esm"],
	dts: true,
	clean: true,
	outDir: "dist",
	noExternal: ["@aikirun/lib"],
});
